"""Topic.parent_topic_id

Revision ID: 1736434732
Revises: 1736080208
Create Date: 2025-01-09 17:58:52.570321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1736434732'
down_revision: Union[str, None] = '1736080208'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('parent_topic_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'topics', 'topics', ['parent_topic_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topics', type_='foreignkey')
    op.drop_column('topics', 'parent_topic_id')
    # ### end Alembic commands ###
