"""wiki_pages_base

Revision ID: 1773769547
Revises: 1773768986
Create Date: 2026-03-17 20:45:47.676126

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1773769547"
down_revision: Union[str, None] = "1773768986"
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wiki_pages",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
    op.add_column("wiki_pages", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.add_column("wiki_pages", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wiki_pages", "deleted_at")
    op.drop_column("wiki_pages", "updated_at")
    op.drop_column("wiki_pages", "created_at")
    # ### end Alembic commands ###
