"""wiki_pages_is_pinned

Revision ID: 1773768986
Revises: 1773766361
Create Date: 2026-03-17 20:36:26.901921

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1773768986"
down_revision: Union[str, None] = "1773766361"
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("wiki_pages", sa.Column("is_pinned", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wiki_pages", "is_pinned")
    # ### end Alembic commands ###
