"""Author changes & Institution

Revision ID: 1730195605
Revises: 1730129429
Create Date: 2024-10-29 12:53:25.208181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1730195605'
down_revision: Union[str, None] = '1730129429'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('authors', sa.Column('institution_id', sa.Integer(), nullable=False))
    op.alter_column('authors', 'email',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('authors', 'phone',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.create_foreign_key(None, 'authors', 'institutions', ['institution_id'], ['id'])
    op.drop_column('authors', 'institution')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('institution', sa.VARCHAR(length=1024), nullable=False))
    op.drop_constraint(None, 'authors', type_='foreignkey')
    op.alter_column('authors', 'phone',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('authors', 'email',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.drop_column('authors', 'institution_id')
    op.drop_table('institutions')
    # ### end Alembic commands ###
