"""DocumentFile.real_file_name

Revision ID: 1730115924
Revises: 1730042231
Create Date: 2024-10-28 14:45:24.093029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1730115924'
down_revision: Union[str, None] = '1730042231'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_files', sa.Column('real_file_name', sa.String(length=512), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_files', 'real_file_name')
    # ### end Alembic commands ###
