"""Document.organization.id

Revision ID: 1730240058
Revises: 1730235952
Create Date: 2024-10-30 01:14:18.100769

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1730240058"
down_revision: Union[str, None] = "1730235952"
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents", sa.Column("organization_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        None, "documents", "organizations", ["organization_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "documents", type_="foreignkey")
    op.drop_column("documents", "organization_id")
    # ### end Alembic commands ###
