"""Document.abstract

Revision ID: 1730129429
Revises: 1730115924
Create Date: 2024-10-28 18:30:29.706721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1730129429'
down_revision: Union[str, None] = '1730115924'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('abstract', sa.String(length=8192), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'abstract')
    # ### end Alembic commands ###
