"""Event.organization_id

Revision ID: 1736080208
Revises: 1736002901
Create Date: 2025-01-05 15:30:08.658126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1736080208'
down_revision: Union[str, None] = '1736002901'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.alter_column('events', 'location',
               existing_type=mysql.VARCHAR(length=1024),
               nullable=True)
    op.alter_column('events', 'event_url',
               existing_type=mysql.VARCHAR(length=2048),
               nullable=True)
    op.create_foreign_key(None, 'events', 'organizations', ['organization_id'], ['id'])
    op.alter_column('talk_notes', 'start_time',
               existing_type=mysql.TIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('talk_notes', 'start_time',
               existing_type=mysql.TIME(),
               nullable=False)
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.alter_column('events', 'event_url',
               existing_type=mysql.VARCHAR(length=2048),
               nullable=False)
    op.alter_column('events', 'location',
               existing_type=mysql.VARCHAR(length=1024),
               nullable=False)
    op.drop_column('events', 'organization_id')
    # ### end Alembic commands ###
